export enum DONOR_STATUS_TYPES{
    REQUESTED = 'REQUESTED',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
    DONATION_COMPLETE = 'DONATION_COMPLETE',
    DONATION_REJECTED = 'DONATION_REJECTED'
}